# Generated by Django 4.1.9 on 2023-06-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_name', models.CharField(max_length=150, verbose_name='student_name')),
                ('teachers_name', models.CharField(max_length=150, verbose_name='student_name')),
                ('semester', models.IntegerField(choices=[(1, '1 Semestre'), (2, '2 Semestre'), (3, '3 Semestre'), (4, '4 Semestre'), (5, '5 Semestre'), (6, '6 Semestre')], verbose_name='semester')),
            ],
        ),
    ]
