# Generated by Django 4.1.9 on 2023-06-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside_event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpresence',
            name='teachers_name',
            field=models.IntegerField(max_length=150, verbose_name='student_name'),
        ),
    ]
